apiVersion: v1
baseDomain: example.com
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: test
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: '{"auths":{"fake":{"auth": "Zm9vOmJhcgo="}}}'
sshKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDWB+KCxrnhCCfncvjDtPM6IPuTc0FjXZ9rw+0+iwB1m1FabDxhzZYUalv89KugMdd1YGQ2rF+MN3CHxI/Yo6M43BEoPKL2bdJSlKf35TzukdfG+vvDPK78mIuHtNlJ7zfCKZpsOvmz51j2PVtPCYlMh+DkeJoA3pd4bAB2Sm8pkw3d+pDm+dh6n6qsO5QYO7HAML+8xm19IGET64DEuwtCl9lRZYExkfGqYg+FZVUCIuXE+leHRLDJSnbNgBIxSO5KVartdB0I6XR5s3qya9wb+6edtHTMIiU6gA4Fm1o725IOqccZt+piPnnqG7Xb/2JIGisd7/FyCphTu1mmdjv+XRteTUegjx4Hs73DyCsIbiDp7nQ5DRhvDmiOxdmirJwq/BwZeTmTlTMymQwVkU+uzEtlU7srG2RYIlqrwsYDwWxLLmHFanhZZ6DC75yR0j0d1bqAF6ELA/3GiPwUfBQhxANnQSRkApHBe7t28ecHtu5pcjCk17YCI6pbCDZhY8E= debian@ws
